project:
  type: website

website:
  title: "nbnav"
  sidebar:
    contents:
      - index.qmd
      - about.qmd
      - file.name.ipynb
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
